openimis/openimis-be-contract_py

contract/__init__.py, contract/models.py, contract/services.py, contract/urls.py
TICKET: [OFS-14](https://openimis.atlassian.net/browse/OFS-14)
=> OFS-14: Added models and services shell

contract/gql/gql_mutations/__init__.py, contract/gql/gql_mutations/contract_mutations.py, contract/gql/gql_mutations/input_types.py, contract/gql/gql_mutations/mutations.py, contract/models.py, contract/schema.py, contract/services.py, contract/tests/gql_tests/__init__.py, contract/tests/gql_tests/mutation_create_tests.py, contract/tests/gql_tests/query_tests.py, contract/tests/services/services_tests.py
In that pull request I want to merge mutation "create contract" with tests written for that mutation in graphQL.
I will change status to "open" if you merge OFS-133 and OFS-144 (https://github.com/openimis/openimis-be-contract_py/pull/5 and https://github.com/openimis/openimis-be-contract_py/pull/6). And after that you can check this PR.
=> OFS:126: mutation "create contract" with tests and fixing some tests

contract/apps.py
IMPORTANT! This should be merged after accepting and merging this PR related to "update contract" service.
https://github.com/openimis/openimis-be-contract_py/pull/8 . Later after merging pull #8  I will change the status of this pull request from "Draft" to the "Open".
In that PR I want to add the rests of perms for contract module.
=> OFS-154: create contract role for admin

contract/gql/gql_mutations/contract_mutations.py, contract/gql/gql_mutations/input_types.py, contract/gql/gql_mutations/mutations.py, contract/schema.py, contract/tests/gql_tests/mutation_create_tests.py, contract/tests/services/services_tests.py
IMPORTANT! This should be merged after accepting and merging this PR related to "update contract" service and add another perms in contract module.
#8 and https://github.com/openimis/openimis-be-contract_py/pull/9 . Later after merging pull #8 and https://github.com/openimis/openimis-be-contract_py/pull/9 I will change the status of this pull request from "Draft" to the "Open".
The order of merging PR:
1. https://github.com/openimis/openimis-be-contract_py/pull/8
2. https://github.com/openimis/openimis-be-contract_py/pull/9
3. this one
In that PR I want to add the "update contract" mutation.
=> OFS-127: 'update contract' mutation

contract/apps.py, contract/services.py, contract/signals.py, contract/tests/services/services_tests.py
IMPORTANT - this should be merged after merging https://github.com/openimis/openimis-be-core_py/pull/39 from core module.
In that PR I want to add 'submit contract' service with contrac signal - used the class from Core module - overridden Signal class.
=> OFS-136: submit contract service and contract signal 

contract/gql/gql_mutations/contract_mutations.py, contract/gql/gql_mutations/input_types.py, contract/gql/gql_mutations/mutations.py, contract/schema.py, contract/tests/gql_tests/mutation_create_tests.py
In that PR I want to add submit contract mutation based on service.
=> OFS-129: adding submit contract mutation based on service

contract/gql/gql_mutations/contract_mutations.py, contract/gql/gql_mutations/input_types.py, contract/gql/gql_mutations/mutations.py, contract/schema.py, contract/services.py, contract/tests/services/services_tests.py
IMPORTANT. It should be merged after https://github.com/openimis/openimis-be-contract_py/pull/17 
In that PR I want to merge both "counter contract" service and mutation. OFS-138 (service) and OFS-131 (mutation)
=> OFS-138: counter contract service (including OFS-131 counter contract mutation)

contract/services.py, contract/signals.py, contract/tests/services/services_tests.py
In that PR I want to add amend service according to wiki page https://openimis.atlassian.net/wiki/spaces/OP/pages/1730740273/Contract+Module?focusedCommentId=2198700039#comment-2198700039.
Amend service:
- check rights
- create a new “amendment“ contract from the last amendement
- increment Amendment of 1 (i.e. 1st amendment will have 1, 2nd: 2 … )
- change status of the previous contract/amendement to 6 “addendum“
Also I made fix to set amount_due on approve contract instead of amount_rectified.
=> OFS-140: amend contract service

contract/config.py, contract/gql/gql_mutations/contract_mutations.py, contract/gql/gql_mutations/input_types.py, contract/gql/gql_mutations/mutations.py, contract/schema.py, contract/services.py, contract/signals.py, contract/tasks.py, contract/tests/services/services_tests.py
That PR https://github.com/openimis/openimis-be_py/pull/26 must be verified and merge before merging this one.
In that PR I want to merge sending payment notification after approving contract via email
=> OFS-196 - send email payment notification

contract/config.py, contract/gql/gql_mutations/contract_mutations.py, contract/gql/gql_mutations/input_types.py, contract/gql/gql_mutations/mutations.py, contract/schema.py, contract/services.py, contract/signals.py, contract/tasks.py, contract/tests/services/services_tests.py
In that PR I want to add amend mutation with some updates after refreshing Contract wiki page by @delcroip (in amend service section) after today's meeting after FS stand-up. Moreover the bulk approve contract mutation was developed (as Nice to have).
Later another fixes related to the Contract wiki page update will be developed.
=> OFS-132: amend mutation, some fixes after wiki page refresh and bulk approve mutation

contract/gql/gql_mutations/contract_mutations.py, contract/gql/gql_mutations/input_types.py, contract/schema.py, contract/tasks.py
TICKET - https://openimis.atlassian.net/browse/OFS-224 - OFS-224
In that PR I want to add "Bulk Counter mutation" graphQl so as to enable bulk action 'counter contract' on frontend.
=> OFS-224: mutation bulk counter contract

README.md, contract/tests/gql_tests/mutation_create_tests.py, contract/tests/services/services_tests.py, setup.py
In that PR I want to add test case for calculation based on Contract module as a "class CalculationContractTest(TestCase):"
That cases checks whether calculation services works correctly based on Contract and whether amount is calculated properly based on CalculationRule of Contribution Valuation (FS 1st Calculation Rule)
Moreover I made some upgrades for tests in Contract module so as to have the base PolicyHolder and PHInsures for that cases with Contract.
also included:
+ adding "calculation" module to the dependencies
=> OFS-226: calculation services tests based on Contract and upgrades in tests

contract/tests/gql_tests/mutation_create_tests.py, contract/tests/services/services_tests.py
ticket https://openimis.atlassian.net/browse/OFS-244 
Please merge this first https://github.com/openimis/openimis-be-calculation_py/pull/11
I want to merge changes in test data due to changes in that PR in Calculation module.
=> OFS-244: changes in tests due to calculation param in JSON

contract/schema.py
Ticket - https://openimis.atlassian.net/browse/OFS-254 - issue 1
In that PR I want to fix default validity filter for Contract entity
=> OFS-254: fixing validity filter in Contract entity 

contract/apps.py, contract/schema.py
TICKET: https://openimis.atlassian.net/browse/OFS-259
In that ticket I want to add perms for contract policy holder portal.
=> OFS-259: Support the policyholder portal perms on Contract

contract/signals.py
TICKET: https://openimis.atlassian.net/browse/OFS-281
requires changes from that PR in Insuree module
=> OFS-281: Create GraphQL queries for the Insuree policy

contract/gql/gql_mutations/contract_mutations.py, contract/gql/gql_mutations/input_types.py
TICKET: https://openimis.atlassian.net/browse/OFS-285
=> OFS-285: Fix bulk action - change approach in bulk mutation in contract

contract/signals.py
TICKET: https://openimis.atlassian.net/browse/OFS-292
part related to changes with User made by BlueSquare
related PR: https://github.com/openimis/openimis-be-policyholder_py/pull/40
=> OFS-292: changes in contract module related to BSquare chanbges with User

contract/signals.py
TICKET: https://openimis.atlassian.net/browse/OE0-74
Required PR to merge: https://github.com/openimis/openimis-be-policy_py/pull/14
In that module the signal (with verify whether policy is linked to fs entities or not) is going to be connected if that module is installed.
This function which is connected to signal checks if policy is related to formal sector entities.
=> OE0-74: added function triggered by signal to check if policy is related to FS

contract/apps.py, contract/gql/gql_mutations/contract_mutations.py, contract/gql/gql_mutations/input_types.py, contract/gql/gql_mutations/mutations.py, contract/schema.py, contract/services.py, contract/tasks.py
TICKET: https://openimis.atlassian.net/browse/OPL-31
such mutation (implemented service is wrapped here) creates invoices for chosen contract
:
=> OPL-31: Create 'createInvoice' service in Contract module

contract/migrations/0017_contract_roles_for_admin.py
TICKET: https://openimis.atlassian.net/browse/OP-461
=> OP-461: added contract roles for admin

contract/migrations/0018_approve_ask_for_change_perms.py, contract/signals.py
TICKET: https://openimis.atlassian.net/browse/OP-478
- fixed 'grace_period' on 'payment received' signal 
- added lacking role for 'counter/approve'
=> OP-478: fixed 'grace_period' on payment received signal, added lacking role approve/counter

contract/migrations/0019_amend_perms.py, contract/services.py
TICKET: https://openimis.atlassian.net/browse/OP-478
fixed amendment case.
=> OP-478: fixed decimal/float operation in 'amendment' section

contract/services.py
part of ticket: https://openimis.atlassian.net/browse/OP-759
=> OP-759: fixed return in service 'create_contract_details_policies'

README.md
part of TICKET: https://openimis.atlassian.net/browse/OP-752
specified requirements to have 'bulk operations' working in this module (Contract)
=> OP-752: modified README - bulk operations section

contract/migrations/0017_contract_roles_for_admin.py, contract/migrations/0018_approve_ask_for_change_perms.py, contract/migrations/0019_amend_perms.py, contract/services.py
Migrations and a small misuse of != vs is not
=> PostgreSQL support

contract/migrations/0001_initial.py, contract/models.py
=> Django 3.1

contract/services.py, contract/signals.py, contract/tests/gql_tests/mutation_create_tests.py, contract/tests/gql_tests/query_tests.py, contract/tests/helpers.py, contract/tests/services/services_tests.py
Changes:
- Changed handling of JSON fields from JSON strings to python dictionaties (Django 3.2 update)
- Fixed TestCase handling (added all missing calls to super.setUpClass, super.setUp, removed unecessary teardowns)
- Removed some unused code/comments/imports
- Fixed code formatting
=> OP-868 Fix CI issues caused by Django 3.2 update

.github/workflows/openmis-module-test.yml, .github/workflows/python-publish.yml, contract/schema.py, contract/services.py
Ticket:
https://openimis.atlassian.net/browse/OTC-963
Changes:
- added check for creating contract with already used code
Note:
- error is not properly caught, it prevents from saving contract with duplicated code but it crashes the website
=> OTC-963: added check for creating duplicated contract

.github/workflows/openmis-module-test.yml, .github/workflows/python-publish.yml, contract/schema.py, contract/services.py
MERGING RELEASE branches
Release release/23.04
=> MERGING RELEASE branches

.github/workflows/openmis-module-test-mssql.yml, .github/workflows/openmis-module-test-psql.yml, contract/tests/gql_tests/query_tests.py
[https://openimis.atlassian.net/browse/OP-1500](https://openimis.atlassian.net/browse/OP-1500)
=> OP-1500 Backend CI are not working

contract/apps.py
https://openimis.atlassian.net/browse/OP-1518
This PR changes the way how config is loaded.
=> OP-1518: load config

contract/gql/gql_mutations/contract_mutations.py, contract/services.py, contract/signals.py, contract/tasks.py, contract/tests/gql_tests/mutation_create_tests.py, contract/tests/services/services_tests.py
MERGING develop into release/24.04
=> MERGING develop into release/24.04
